create table if not exists public.respuestas_modelo_hibrido (
  id bigint generated by default as identity primary key,
  codigo_participante text not null,
  ciudad text,
  edad_mascota integer,
  edad_persona integer,
  genero text,
  estrato_social text,
  modelo text not null,
  claridad text,
  adelanto text,
  copago text,
  opinion_copago_hibrido text,
  claridad_copago_reembolso text,
  comentario text,
  mejora text,
  factura_simulada numeric,
  modelo_simulado text,
  copago_simulado numeric,
  fecha timestamptz not null default now(),
  version_prototipo text not null default '1.0'
);

alter table public.respuestas_modelo_hibrido
  add column if not exists genero text;

alter table public.respuestas_modelo_hibrido enable row level security;

drop policy if exists "Permitir insertar respuestas anonimas" on public.respuestas_modelo_hibrido;
create policy "Permitir insertar respuestas anonimas"
  on public.respuestas_modelo_hibrido for insert
  to anon
  with check (true);

create index if not exists respuestas_modelo_hibrido_fecha_idx
  on public.respuestas_modelo_hibrido (fecha desc);
